# Generated by Django 4.0.6 on 2022-07-26 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todoitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='name',
            new_name='task',
        ),
    ]
